// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © jupiterchen


//@version=6
strategy('ADX&DI', overlay = true)
// 输入参数
len = input.int(14, title = 'ADX Length') // ADX周期长度
adxThreshold = input.int(20, title = 'ADX Threshold') // ADX判断趋势的阈值

macdFastLength = input.int(12, title = 'MACD Fast Length') // MACD快速线长度
macdSlowLength = input.int(26, title = 'MACD Slow Length') // MACD慢速线长度
macdSignalSmoothing = input.int(9, title = 'MACD Signal Smoothing') // MACD信号线平滑

TrueRange = math.max(math.max(high - low, math.abs(high - nz(close[1]))), math.abs(low - nz(close[1])))
DirectionalMovementPlus = high - nz(high[1]) > nz(low[1]) - low ? math.max(high - nz(high[1]), 0) : 0
DirectionalMovementMinus = nz(low[1]) - low > high - nz(high[1]) ? math.max(nz(low[1]) - low, 0) : 0

SmoothedTrueRange = 0.0
SmoothedTrueRange := nz(SmoothedTrueRange[1]) - nz(SmoothedTrueRange[1]) / len + TrueRange

SmoothedDirectionalMovementPlus = 0.0
SmoothedDirectionalMovementPlus := nz(SmoothedDirectionalMovementPlus[1]) - nz(SmoothedDirectionalMovementPlus[1]) / len + DirectionalMovementPlus

SmoothedDirectionalMovementMinus = 0.0
SmoothedDirectionalMovementMinus := nz(SmoothedDirectionalMovementMinus[1]) - nz(SmoothedDirectionalMovementMinus[1]) / len + DirectionalMovementMinus

DIPlus = SmoothedDirectionalMovementPlus / SmoothedTrueRange * 100
DIMinus = SmoothedDirectionalMovementMinus / SmoothedTrueRange * 100
DX = math.abs(DIPlus - DIMinus) / (DIPlus + DIMinus) * 100
ADX = ta.sma(DX, len)

// 计算MACD
[macdLine, signalLine, _] = ta.macd(close, macdFastLength, macdSlowLength, macdSignalSmoothing)

// 策略条件
buyCondition = DIPlus > DIMinus and ADX > adxThreshold and macdLine > signalLine // 买入条件
sellCondition = DIMinus > DIPlus and ADX > adxThreshold and macdLine < signalLine // 卖出条件

start_date = timestamp(2018, 10, 1, 0, 0) // 开始时间

// 检查当前持仓状态
inLong = strategy.position_size > 0
inShort = strategy.position_size < 0


if time >= start_date
    // 执行交易
    if (buyCondition)
        strategy.entry('Buy', strategy.long)
        // label.new(bar_index, low, text = 'Buy', style = label.style_label_up, color = color.green, textcolor = color.white, size = size.small)

    if (sellCondition and strategy.position_size > 0) 
        strategy.close('Buy')
        // label.new(bar_index, high, text = 'Sell', style = label.style_label_down, color = color.red, textcolor = color.white, size = size.small)

